const ss= [
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/jmpivohwalgtoe74wv4k",
    "id" : 0,
    "shopName" : "Anjappar",
    "cuisines" : ["Chettinad"],
    "rating" : 3.8 ,
    "delivery" : 21 ,
    "price" : 300,
    "offer": 60 ,
    "shopItems" : [
      {
    'dishName' : "Paneer Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/hvmuurctk8gclgfigh1o" ,
    'price' : "211.30" ,
    },
    {
    'dishName' : "Gobi Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/cxidjxwucn2dky8u1ql5" ,
    'price' : "228" ,
    },
    {
    'dishName' : "Gobi 65" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/fjbvjbq9mild4wfzbgrv" ,
    'price' : "230" ,
    },
    {
    'dishName' : "Chilly Mushroom Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/sqiycvr4eg63herbckqt" ,
    'price' : "180" ,
    },
    {
    'dishName' : "Chicken Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/izpvqy9oueu3wmxnv7ns" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Garlic Chicken Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yfh2rkqassukzb1fokkg" ,
    'price' : "190" ,
    },
    {
    'dishName' : "Chicken Lollipop" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/umleijpft3jycmajhz2i" ,
    'price' : "140" ,
    },
    {
    'dishName' : "Chicken Lollipop Saucy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yl6vwwyhokeyt5vxlitq" ,
    'price' : "160" ,
    },
    {
    'dishName' : "Chicken 65 [boneless]" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uistekbi4c6twshjwttx" ,
    'price' : "210" ,
    },
    {
    'dishName' : "Chilly Chicken Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ur01ykci7zxpfday7unh" ,
    'price' : "160" ,
    },
    {
    'dishName' : "Chicken Tikka" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/itu7pbvgj9hvthle9wo8" ,
    'price' : "256" ,
    },
    {
    'dishName' : "Grilled Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/mblmccl8pwslvo1ukxzt" ,
    'price' : "290" ,
    },
    {
    'dishName' : "Tandoori Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/oecxmurnejxswadfmd78" ,
    'price' : "288" ,
    },
    {
    'dishName' : "Paneer Butter Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/qxwdkwqfebyhyvgcirxn" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Chicken Tikka Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/gjilzpse8c5d7bhzexqk" ,
    'price' : "230" ,
    },
    {
    'dishName' : "Butter Chicken Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uvrpfoyjyk4ilhtwxirc" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Kadai Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yq6sxppa8zqrkwmn7fr5" ,
    'price' : "270" ,
    },
    {
    'dishName' : "Chicken Manchurian Gravy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ayxmkrjkuxvabswjnn6a" ,
    'price' : "290" ,
    },
    {
    'dishName' : "Chilly Chicken Gravy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/vrxehavdwj5nxayjcinf" ,
    'price' : "260" ,
    }
  ]
  ,
    "area" : "Vannarpettai",
    "city" : "Tirunelveli", 
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/wzxwkbnvij8lacgpxbtq",
    "id" : 1,
    "shopName" : "Annapoorna Garden Restaurant ",
    "cuisines" : ["Chinese, South Indian, Ice Cream"],
    "rating" : 4.3,
    "delivery" : 13 ,
    "price" : 250,
    "offer": 60 ,
    "shopItems" : [
      {
      'dishName' : "Onion Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/zqwcbnpl31xc3m3kahws" ,
      'price' : "260" ,
      },
      {
      'dishName' : "Masal Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yhslimbg6v4lm7f61zjq" ,
      'price' : "230" ,
      },
      {
      'dishName' : "Five Taste Uthappam" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/0d0a34deaa276d8cb864348e1c4b022f" ,
      'price' : "180" ,
      },
      {
      'dishName' : "Tomato Uthappam" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/voecnct5dl0tzxruyetj" ,
      'price' : "190" ,
      },
      {
      'dishName' : "Idly 2 Pcs" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/munbih4ewnwgu5yc0kox" ,
      'price' : "120" ,
      },
      {
      'dishName' : "Papper Roast" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/mjwzfxv7dfey1tlym5xx" ,
      'price' : "160" ,
      },
      {
      'dishName' : "Onion Uthappam" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/advgppdvej39qpkiktre" ,
      'price' : "180" ,
      },
      {
      'dishName' : "Rava Dosa 1" ,
      'dishImg' : "Onion Rava 1" ,
      'price' : "90" ,
      },
      {
      'dishName' : "Utthappam" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/lzvgh4pqgstgeztu427f" ,
      'price' : "160" ,
      },
      {
      'dishName' : "Ghee Roast" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/lybmsoyjgoumpf5libqe" ,
      'price' : "160" ,
      },
      {
      'dishName' : "Podi Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/rvowtzghviwslkjosjck" ,
      'price' : "120" ,
      },
      {
      'dishName' : "Ellu Podi Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/emd7ejtjuhoykrdlfwpo" ,
      'price' : "120" ,
      },
      {
      'dishName' : "Coffee" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/tzy7vldukl1aw9gbpqej" ,
      'price' : "53" ,
      },
      {
      'dishName' : "Tea" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/qz9delujurq2mjovkqfj" ,
      'price' : "25" ,
      },
      {
      'dishName' : "Milk" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/jufc5hcqpdyk0zsh5a8d" ,
      'price' : "25" ,
      },
      {
      'dishName' : "Batham Milk" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/wm2f72l46qn461odvc4i" ,
      'price' : "90" ,
      },
      {
      'dishName' : "Valai Poo Onion Podi Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/zsqx0fkijqtpfdhhlnfr" ,
      'price' : "160" ,
      },
      {
      'dishName' : "Kerala Masal Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/gudezamdyorymbhbdvwv" ,
      'price' : "150" ,
      },
      {
      'dishName' : "Kesari [100gram" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/sgkytivqxr0pixiydj1k" ,
      'price' : "160" ,
      },
      {
      'dishName' : "Ghee Tower Roast" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/bu4tqacfsxbzpxkjhgm9" ,
      'price' : "130" ,
      },
      {
      'dishName' : "Podi Uthappam" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/wjqvct7x7tfx4qq14tip" ,
      'price' : "130" ,
      },
      {
      'dishName' : "Muscoth Halva" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/vwqti5dggdifp3ljw9di" ,
      'price' : "120" ,
      },
      {
      'dishName' : "Chappathi With Kadalaikari" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/nr1qcagg2zdykgf6zqsl" ,
      'price' : "120" ,
      },
      {
      'dishName' : "Chappathi Kuruma" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/twacurogvjf7m5zjyvge" ,
      'price' : "100" ,
      },
      {
      'dishName' : "Curd Vadai" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/puixfvejedvlmq360jll" ,
      'price' : "90" ,
      },
      {
      'dishName' : "Appam Kadalaikari" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/wmrpqunmq2afgiulawm0" ,
      'price' : "120" ,
      },
      {
      'dishName' : "Poori Set Masala" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/qe4c2vcjfclh9vco2hlx" ,
      'price' : "130" ,
      },
      {
      'dishName' : "Gheepongal" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ywxy5etaagrrtdwemrgf" ,
      'price' : "100" ,
      },
      {
      'dishName' : "Elaneer Payasam" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/jxkyk8nm2k6y6ku2o7ux" ,
      'price' : "90" ,
      },
      {
      'dishName' : "Kerala Masala Dosai" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/krdj1tgdlp8faikqjvqm" ,
      'price' : "155" ,
      },
      {
      'dishName' : "Ulunda Vadai" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/jh9xcbnqq4q28oh3cogl" ,
      'price' : "33" ,
      },
      {
      'dishName' : "Dal Vadai" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ugaqslqexu7tkfuqmils" ,
      'price' : "23" ,
      },
      {
      'dishName' : "Rava Dosa" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/x8yollakjbd9u8igoknb" ,
      'price' : "32" ,
      },
      {
      'dishName' : "Onion Rava" ,
      'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i9jybr811mge5zzclvgr" ,
      'price' : "80" ,
      },
    ],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bbobhzmu0xpsk56hx23b",
    "id" : 2,
    "shopName" : "Noon Arabian Grill",
    "cuisines" : ["Biryani, Indian, North Indian, Fast Food, Chinese, Arabian"],
    "rating" : 4.1,
    "delivery" : 15 ,
    "price" : 200 ,
    "offer": 40 ,
    "shopItems" : [
      {
        'dishName' : "Egg Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/jeaadlgmp3qepioqca90" ,
        'price' : "100" ,
      },
      {
        'dishName' : "Chicken Schezwan Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/xyiqudgqhbtosaswstub" ,
        'price' : "145" ,
      },
      {
        'dishName' : "Chicken Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/aihfr4e9igs1u3cqljbo" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Mixed Non veg Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/xtdgyqd5isqmrtpyffyd" ,
        'price' : "155" ,
      },
      {
        'dishName' : "Veg Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/g42cyhtu06nqhqdzzsih" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Paneer Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/sjmqolcmosf3t5qne9il" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Egg Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/jeaadlgmp3qepioqca90" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Chicken Schezwan Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/xyiqudgqhbtosaswstub" ,
        'price' : "159" ,
      },
      {
        'dishName' : "Chicken Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/aihfr4e9igs1u3cqljbo" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Mixed Non veg Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/xtdgyqd5isqmrtpyffyd" ,
        'price' : "140" ,
      },
      {
        'dishName' : "Veg Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/g42cyhtu06nqhqdzzsih" ,
        'price' : "166" ,
      },
      {
        'dishName' : "Paneer Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/sjmqolcmosf3t5qne9il" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Prawns Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/bml1lz0sz3d6bq0ntml0" ,
        'price' : "120" ,
      },
      {
        'dishName' : "Mushroom Fried Rice" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/ovimldmh4zcf4uzm5q5g" ,
        'price' : "155" ,
      },
      {
        'dishName' : "Thalassery Chicken Biryani" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/cwk79hrnzvwbt3bnmipp" ,
        'price' : "260" ,
      },
      {
        'dishName' : "Thalassery Egg Biryani" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/op7dkax7is5rg6gwnwdg" ,
        'price' : "160" ,
      },
      {
        'dishName' : "Ambur Egg Biryani" ,
        'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,e_grayscale,c_fit/tsbiyn4efmemciv5lb41" ,
        'price' : "188" ,
      },
    ],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/u7mfwq3mymmissidholz",
    "id" : 3,
    "shopName" : "Arabian Hot Grill",
    "cuisines" : ["Chinese, North Indian, Burgers, Ice Cream, Pizzas, Biryani"],
    "rating" : 4.2,
    "delivery" : 23 ,
    "price" : 250 ,
    "offer": 30 ,
    "shopItems" : [
      {
    'dishName' : "Paneer Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/hvmuurctk8gclgfigh1o" ,
    'price' : "211.30" ,
    },
    {
    'dishName' : "Gobi Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/cxidjxwucn2dky8u1ql5" ,
    'price' : "228" ,
    },
    {
    'dishName' : "Gobi 65" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/fjbvjbq9mild4wfzbgrv" ,
    'price' : "230" ,
    },
    {
    'dishName' : "Chilly Mushroom Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/sqiycvr4eg63herbckqt" ,
    'price' : "180" ,
    },
    {
    'dishName' : "Chicken Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/izpvqy9oueu3wmxnv7ns" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Garlic Chicken Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yfh2rkqassukzb1fokkg" ,
    'price' : "190" ,
    },
    {
    'dishName' : "Chicken Lollipop" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/umleijpft3jycmajhz2i" ,
    'price' : "140" ,
    },
    {
    'dishName' : "Chicken Lollipop Saucy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yl6vwwyhokeyt5vxlitq" ,
    'price' : "160" ,
    },
    {
    'dishName' : "Chicken 65 [boneless]" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uistekbi4c6twshjwttx" ,
    'price' : "210" ,
    },
    {
    'dishName' : "Chilly Chicken Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ur01ykci7zxpfday7unh" ,
    'price' : "160" ,
    },
    {
    'dishName' : "Chicken Tikka" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/itu7pbvgj9hvthle9wo8" ,
    'price' : "256" ,
    },
    {
    'dishName' : "Grilled Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/mblmccl8pwslvo1ukxzt" ,
    'price' : "290" ,
    },
    {
    'dishName' : "Tandoori Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/oecxmurnejxswadfmd78" ,
    'price' : "288" ,
    },
    {
    'dishName' : "Paneer Butter Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/qxwdkwqfebyhyvgcirxn" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Chicken Tikka Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/gjilzpse8c5d7bhzexqk" ,
    'price' : "230" ,
    },
    {
    'dishName' : "Butter Chicken Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uvrpfoyjyk4ilhtwxirc" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Kadai Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yq6sxppa8zqrkwmn7fr5" ,
    'price' : "270" ,
    },
    {
    'dishName' : "Chicken Manchurian Gravy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ayxmkrjkuxvabswjnn6a" ,
    'price' : "290" ,
    },
    {
    'dishName' : "Chilly Chicken Gravy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/vrxehavdwj5nxayjcinf" ,
    'price' : "260" ,
    }
  ],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bkjibtgotmkpwmustjs8",
    "id" : 4,
    "shopName" : "Dindugal Thalapakatti",
    "cuisines" : ["Biryani, Barbecue, South Indian, Chinese, North Indian"],
    "rating" : 3.9 ,
    "delivery" : 23,
    "price" :300 ,
    "offer": 25 ,
    "shopItems" : [
      {
    'dishName' : "Paneer Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/hvmuurctk8gclgfigh1o" ,
    'price' : "211.30" ,
    },
    {
    'dishName' : "Gobi Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/cxidjxwucn2dky8u1ql5" ,
    'price' : "228" ,
    },
    {
    'dishName' : "Gobi 65" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/fjbvjbq9mild4wfzbgrv" ,
    'price' : "230" ,
    },
    {
    'dishName' : "Chilly Mushroom Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/sqiycvr4eg63herbckqt" ,
    'price' : "180" ,
    },
    {
    'dishName' : "Chicken Manchurian Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/izpvqy9oueu3wmxnv7ns" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Garlic Chicken Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yfh2rkqassukzb1fokkg" ,
    'price' : "190" ,
    },
    {
    'dishName' : "Chicken Lollipop" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/umleijpft3jycmajhz2i" ,
    'price' : "140" ,
    },
    {
    'dishName' : "Chicken Lollipop Saucy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yl6vwwyhokeyt5vxlitq" ,
    'price' : "160" ,
    },
    {
    'dishName' : "Chicken 65 [boneless]" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uistekbi4c6twshjwttx" ,
    'price' : "210" ,
    },
    {
    'dishName' : "Chilly Chicken Dry" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ur01ykci7zxpfday7unh" ,
    'price' : "160" ,
    },
    {
    'dishName' : "Chicken Tikka" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/itu7pbvgj9hvthle9wo8" ,
    'price' : "256" ,
    },
    {
    'dishName' : "Grilled Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/mblmccl8pwslvo1ukxzt" ,
    'price' : "290" ,
    },
    {
    'dishName' : "Tandoori Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/oecxmurnejxswadfmd78" ,
    'price' : "288" ,
    },
    {
    'dishName' : "Paneer Butter Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/qxwdkwqfebyhyvgcirxn" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Chicken Tikka Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/gjilzpse8c5d7bhzexqk" ,
    'price' : "230" ,
    },
    {
    'dishName' : "Butter Chicken Masala" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uvrpfoyjyk4ilhtwxirc" ,
    'price' : "260" ,
    },
    {
    'dishName' : "Kadai Chicken" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/yq6sxppa8zqrkwmn7fr5" ,
    'price' : "270" ,
    },
    {
    'dishName' : "Chicken Manchurian Gravy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/ayxmkrjkuxvabswjnn6a" ,
    'price' : "290" ,
    },
    {
    'dishName' : "Chilly Chicken Gravy" ,
    'dishImg' : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/vrxehavdwj5nxayjcinf" ,
    'price' : "260" ,
    }
  ],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/bdcd233971b7c81bf77e1fa4471280eb",
    "id" : 5,
    "shopName" : "KFC",
    "cuisines" : ["Burgers, Biryani, American, Snacks, Fast Food"],
    "rating" : 4.5 ,
    "delivery" : 18 ,
    "price" :350 ,
    "offer": 10 ,
    "shopItems" : ,
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ijjb8hhu1231kheev0rg",
    "id" : 6,
    "shopName" : "HOTEL NEW RUCHI (HNR) -Near passport office",
    "cuisines" : ["Chinese, North Indian, South Indian, Biryani"],
    "rating" : 3.5,
    "delivery" : 13 ,
    "price" :250 ,
    "offer": 15 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fgs3f0cw1mdsfvs0gigv",
    "id" : 7,
    "shopName" : "Nanjil Briyani",
    "cuisines" : ["Chinese, Indian, Biryani"],
    "rating" : 4.3,
    "delivery" : 18 ,
    "price" :250 ,
    "offer":  60 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/faxfc2zwpgtidrs2reoi",
    "id" : 8,
    "shopName" : "Sri Uma Sankar Hotel",
    "cuisines" : ["Desserts, Chinese, North Indian, South Indian, Ice Cream, Biryani"],
    "rating" : 4,
    "delivery" : 23,
    "price" :300,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pz9cersrl3oxrhqy7rlo",
    "id" : 9,
    "shopName" : "Hotel New Ruchi",
    "cuisines" : ["Chinese, North Indian, South Indian, Biryani"],
    "rating" : 3.8,
    "delivery" : 25 ,
    "price" :250,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/lxeooynvlgwswn30xt7g",
    "id" : 10,
    "shopName" : "Hotel Anandha Bhavan",
    "cuisines" : ["Chinese, North Indian, South Indian"],
    "rating" : 4.3,
    "delivery" : 23 ,
    "price" :300 ,
    "offer":  50 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/wzg0cwrbkrala0cr0jiw",
    "id" : 11,
    "shopName" : "Black Forest",
    "cuisines" : ["Desserts, Snacks, Bakery"],
    "rating" : 4.5,
    "delivery" : 10 ,
    "price" :300 ,
    "offer": 40 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/tbtzwaixglq0xbikx2jp",
    "id" : 12,
    "shopName" : "Shah Bucket Biryani",
    "cuisines" : ["North Indian, Biryani"],
    "rating" : 3.5,
    "delivery" : 16,
    "price" :230 ,
    "offer": 30 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ab979bffbd658e74de650a15ca0092a3",
    "id" : 13,
    "shopName" : "Oven Story Pizza",
    "cuisines" : ["Italian"],
    "rating" : 4.1,
    "delivery" : 20 ,
    "price" :150 ,
    "offer": 15,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/glpmhlojsnrnfy7cmaiz",
    "id" : 14,
    "shopName" : "Ashife biryani",
    "cuisines" : ["Desserts, Chinese, North Indian, South Indian, Ice Cream, Biryani"],
    "rating" : 4.1,
    "delivery" : 20,
    "price" : 250 ,
    "offer": 40 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fhnlhaojh3hepfk7jjbb",
    "id" : 15,
    "shopName" : "dominos pizza",
    "cuisines" : "Pizzas, Italian, Pastas, Desserts",
    "rating" : 4.5,
    "delivery" : 14 ,
    "price" : 120,
    "offer": 30 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/83650e6ca1465c58063a70ad22be4f28",
    "id" : 16,
    "shopName" : "ambur star biyani",
    "cuisines" : "Biryani",
    "rating" : 4,
    "delivery" : 13 ,
    "price" :200 ,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fvhsmfiipeaovqsunl29",
    "id" : 17,
    "shopName" : "kings kitchen",
    "cuisines" : "South Indian, Chinese, Grill, Tandoor",
    "rating" : 3.,
    "delivery" : 10 ,
    "price" :150,
    "offer": 25,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fejciuebgbtbbbxeog6s",
    "id" : 18,
    "shopName" : "Hotel hari prasad",
    "cuisines" : "Pastas, Chinese, North Indian, South Indian, Ice Cream, Pizzas, Biryani, Sweets",
    "rating" : 4,
    "delivery" : 18 ,
    "price" :100 ,
    "offer": 15 ,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/yiaypenril7pcy2steix",
    "id" : 19,
    "shopName" : "the good bowl",
    "cuisines" : "North Indian, Punjabi, Biryani, Chinese, Beverages, Desserts, Jain, Indian, Hyderabadi, Mughlai",
    "rating" : 3.3,
    "delivery" : 22,
    "price" :150,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pw5gnmgwcsvrajafn1rc",
    "id" : 20,
    "shopName" : "muthu mess",
    "cuisines" : "Desserts, South Indian",
    "rating" : 3.2,
    "delivery" : 26,
    "price" :85,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },{
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/x98pgsdw1ylsjerf2idu",
    "id" : 21,
    "shopName" : "cafe mc2",
    "cuisines" : "Pastas, Chinese, Burgers, Ice Cream, Pizzas",
    "rating" : 4.3,
    "delivery" : 14,
    "price" :250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/hwrgph8ab9ydmzcdqudo",
    "id" : 22,
    "shopName" : "behrouz biryani",
    "cuisines" : "Biryani, Mughlai, Lucknowi, Kebabs, Hyderabadi, North Indian, Persian, Desserts",
    "rating" : 4.3,
    "delivery" : 25,
    "price" :250,
    "offer": 35,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/mmlqwrfwa2hlhkhx7zdw",
    "id" : 23,
    "shopName" : "Sri Madhuram Hot Spot (Thiyagarajanagar)",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Ice Cream, Sweets",
    "rating" : 3,
    "delivery" : 15,
    "price" :120,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/hvpsrfsbkl0ehvehlres",
    "id" : 24,
    "shopName" : "faasos",
    "cuisines" : "Fast Food, North Indian, Street Food, Desserts",
    "rating" : 3,
    "delivery" : 18 ,
    "price" :150 ,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/be2bfa3b5dde1e71b41144e9b62878a9",
    "id" : 25,
    "shopName" : "halal chicken",
    "cuisines" : "Biryani, Indian",
    "rating" : 4,
    "delivery" : 25,
    "price" :160,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/7c51efd1c5a12b7925e428a87977f85d",
    "id" : 26,
    "shopName" : "sweet truth",
    "cuisines" : "Bakery, Desserts",
    "rating" : 3.8,
    "delivery" : 13,
    "price" :60,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/mpcoii2rer8xmrtzwlm4",
    "id" : 27,
    "shopName" : "hotel ajees rowther biryani",
    "cuisines" : "Chinese, North Indian, South Indian, Biryani",
    "rating" : 3,
    "delivery" : 18,
    "price" :180,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ub4bwctyul46cvyfqvy3",
    "id" : 28,
    "shopName" : "hotel zero degree",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Biryani",
    "rating" : 3.9,
    "delivery" : 20,
    "price" :180,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },

  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xcxly59wiod9vyntj9jy",
    "id" : 29,
    "shopName" : "biryani life",
    "cuisines" : "Biryani, Hyderabadi, Lucknowi, North Indian, Mughlai, Desserts",
    "rating" : 4.3,
    "delivery" : 23,
    "price" : 250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/g8xoexoudmkjewpouyki",
    "id" : 30,
    "shopName" : "hotel aryan bhavan",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Ice Cream, Biryani",
    "rating" : 3.3,
    "delivery" : 26,
    "price" :250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/smy88auwfhs45eprcsao",
    "id" : 31,
    "shopName" : "fish n life",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Ice Cream, Biryani",
    "rating" : 4,
    "delivery" : 23,
    "price" :310,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dmk1ritnvatjiyjtbsg7",
    "id" : 32,
    "shopName" : "border poratto stall",
    "cuisines" : "Chinese, North Indian, South Indian, Biryani",
    "rating" : 4.1,
    "delivery" : 23,
    "price" :120,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/d6m9ojhw3o0n9tjnjqg5",
    "id" : 33,
    "shopName" : "hotel palmyra grand suite",
    "cuisines" : "Chinese, North Indian, Ice Cream, Biryani",
    "rating" : 4.3,
    "delivery" : 20,
    "price" : 250,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/y3pcztsovqjynjii8dft",
    "id" : 34,
    "shopName" : "nellai saravana bhava",
    "cuisines" : "Desserts, Chinese, South Indian, Ice Cream, Sweets",
    "rating" : 4.5,
    "delivery" : 19,
    "price" : 150,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/9930cd0f850cff46b0c079e19aee23c2",
    "id" : 35,
    "shopName" : "aruvi bakery and sweets",
    "cuisines" : "Pastas, Desserts, Chinese, Burgers, Ice Cream, Pizzas, Sweets",
    "rating" : 3.8,
    "delivery" : 19,
    "price" : 260,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ii6ujrny6ghywh2pljwl",
    "id" : 36,
    "shopName" : "firangi bake",
    "cuisines" : "Italian, Mexican, Pastas",
    "rating" : 4.6,
    "delivery" : 23,
    "price" :250,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/rcqimcni8a9gyaynlbcf",
    "id" : 37,
    "shopName" : "chakra multicuisine restaurant",
    "cuisines" : "Indian, Chinese",
    "rating" : 3.9,
    "delivery" : 19,
    "price" :150,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/aftexy8cpionq0839te7",
    "id" : 38,
    "shopName" : "urban dhaba",
    "cuisines" : "Pastas, Desserts, Chinese, North Indian, South Indian, Burgers, Ice Cream, Pizzas",
    "rating" : 3.7,
    "delivery" : 21,
    "price" : 150,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/qajirtblx0lebdr952jy",
    "id" : 39,
    "shopName" : "veg dawaat by behrouz",
    "cuisines" : "Biryani, Mughlai, Lucknowi, Kebabs, Hyderabadi, North Indian, Persian, Desserts",
    "rating" : 3.9,
    "delivery" : 25,
    "price" :180,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ub4bwctyul46cvyfqvy3",
    "id" : 40,
    "shopName" : "hotel zero degree",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Biryani",
    "rating" : 3.9,
    "delivery" : 20,
    "price" :180,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },

  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/xcxly59wiod9vyntj9jy",
    "id" : 41,
    "shopName" : "biryani life",
    "cuisines" : "Biryani, Hyderabadi, Lucknowi, North Indian, Mughlai, Desserts",
    "rating" : 4.3,
    "delivery" : 23,
    "price" : 250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/g8xoexoudmkjewpouyki",
    "id" : 42,
    "shopName" : "hotel aryan bhavan",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Ice Cream, Biryani",
    "rating" : 3.3,
    "delivery" : 26,
    "price" :250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/smy88auwfhs45eprcsao",
    "id" : 43,
    "shopName" : "fish n life",
    "cuisines" : "Desserts, Chinese, North Indian, South Indian, Ice Cream, Biryani",
    "rating" : 4,
    "delivery" : 23,
    "price" :310,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dmk1ritnvatjiyjtbsg7",
    "id" : 44,
    "shopName" : "border poratto stall",
    "cuisines" : "Chinese, North Indian, South Indian, Biryani",
    "rating" : 4.1,
    "delivery" : 23,
    "price" :120,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/d6m9ojhw3o0n9tjnjqg5",
    "id" : 45,
    "shopName" : "hotel palmyra grand suite",
    "cuisines" : "Chinese, North Indian, Ice Cream, Biryani",
    "rating" : 4.3,
    "delivery" : 20,
    "price" : 250,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/gonsfq4jssc1fb49rryp",
    "id" : 46,
    "shopName" : "a n hotel",
    "cuisines" : "Chinese, North Indian, South Indian, Biryani",
    "rating" : 4.2,
    "delivery" : 16,
    "price" :180,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },{
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/lcll1fj67i260skpzugk",
    "id" : 47,
    "shopName" : "food engine",
    "cuisines" : "Chinese, North Indian, Burgers, Ice Cream, Pizzas",
    "rating" : 3.9,
    "delivery" : 3.5,
    "price" :130,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/83650e6ca1465c58063a70ad22be4f28",
    "id" : 48,
    "shopName" : "ambur biryani",
    "cuisines" : "biryani",
    "rating" : 3.9,
    "delivery" : 16,
    "price" :150,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/itn7bjrvwbdyhqpvjkl0",
    "id" : 49,
    "shopName" : "platz 369",
    "cuisines" : "Chinese, North Indian, Burgers, Ice Cream, Pizzas",
    "rating" : 4.6,
    "delivery" : 23,
    "price" :160,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fdf564e0081566e287cfa59622266b1a",
    "id" : 50,
    "shopName" : "oyalo pizza",
    "cuisines" : "Pizzas, Desserts, Beverages",
    "rating" : 4.3,
    "delivery" : 23,
    "price" :160,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ywevcxysieoggkzpwtp1",
    "id" : 51,
    "shopName" : "alaya bakery and sweets",
    "cuisines" : "Pastas, Desserts, Chinese, Burgers, Ice Cream, Pizzas, Sweets",
    "rating" : 3.8,
    "delivery" : 18,
    "price" :250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/icf68evzgivfedmdryuo",
    "id" : 52,
    "shopName" : "luara chicken",
    "cuisines" : "Chinese, North Indian, South Indian, Biryani",
    "rating" : 4.2,
    "delivery" : 26,
    "price" :170,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },{
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/mp0zqteuom8xptb732v2",
    "id" : 53,
    "shopName" : "a1 poratta stall",
    "cuisines" : "Chinese, North Indian, South Indian",
    "rating" : 4.6,
    "delivery" : 19,
    "price" :160,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ndark0fnxqqwqdapooln",
    "id" : 54,
    "shopName" : "juic time restaurant",
    "cuisines" : "Chinese, Ice Cream",
    "rating" : 4.1,
    "delivery" : 16,
    "price" :100,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ulku4hegim4mzjmzbtt9",
    "id" : 55,
    "shopName" : "melon sweets and bakery",
    "cuisines" : "Bakery, Sweets, Chaat, American",
    "rating" : 3.5,
    "delivery" : 16,
    "price" :130,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/b95031638c72d00f1bbf8828db4d7cfd",
    "id" : 56,
    "shopName" : "just fresh",
    "cuisines" : "Desserts, Chinese, Burgers, Pizzas",
    "rating" : 3.6,
    "delivery" : 18,
    "price" :120,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "Desserts, Chinese, Burgers, Pizzas",
    "id" : 57,
    "shopName" : "vinayaga dosa corner",
    "cuisines" : "South Indian",
    "rating" : 4.2,
    "delivery" : 19,
    "price" :90,
    "offer": 10,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },

  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dih5hqbuqv3tjakcqhmv",
    "id" : 58,
    "shopName" : "ibaco",
    "cuisines" : "ice cream , cakes",
    "rating" : 4.6,
    "delivery" : 4.3,
    "price" : 360,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/da2592e0d25f079cbf9aedf436cabf6f",
    "id" : 59,
    "shopName" : "aranmanai virundhu",
    "cuisines" : "Biryani, North Indian",
    "rating" : 3.9,
    "delivery" : 23,
    "price" :250,
    "offer": 60,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/zpjsjpaovno2jj9rxwae",
    "id" : 60,
    "shopName" : "belgian waffers",
    "cuisines" : "Pastas, Desserts, Chinese, Burgers, Ice Cream, Pizzas",
    "rating" : 4.3,
    "delivery" : 16 ,
    "price" :190,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/mmtlklv3f2jsw4fssobk",
    "id" : 61,
    "shopName" : "sithi kitchen",
    "cuisines" : "Chinese, North Indian, South Indian, Biryani",
    "rating" : 4.1,
    "delivery" : 23,
    "price" : 260,
    "offer": 30,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/r5mxsmwptjyucszknpmu",
    "id" : 62,
    "shopName" : "meat and eat",
    "cuisines" : "Chinese, Burgers, Ice Cream",
    "rating" : 4.1,
    "delivery" : 23,
    "price" :180,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
  {
    "img" : "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/awi8qq62fmyuuykznwjl",
    "id" : 63,
    "shopName" : "renjun hotel",
    "cuisines" : "Chinese, North Indian, Biryani",
    "rating" : 4.2,
    "delivery" :16 ,
    "price" :150,
    "offer": 20,
    "shopItems" : [],
    "area" : "Vannarpettai",
    "city" : "Tirunelveli",
  },
]
